# Generated by Django 4.1.2 on 2022-10-20 18:27

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_announcement_news', models.CharField(choices=[('ОБ', 'Объявление'), ('НО', 'Новость')], default='НО', max_length=2)),
                ('publication_time_publication', models.DateTimeField(auto_now_add=True)),
                ('publication_header_announcement_news', models.CharField(max_length=255)),
                ('publication_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('publication_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_text', models.TextField(default='Текст отклика отсутствует')),
                ('reaction_time_publication', models.DateTimeField(auto_now_add=True)),
                ('reaction_status', models.CharField(choices=[('РА', 'Рассматривается'), ('ПР', 'Принят'), ('ОТ', 'Отклонён')], default='РА', max_length=2)),
                ('reaction_to_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitelogic.publication')),
                ('reaction_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PublicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitelogic.category')),
                ('pc_publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitelogic.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_categories',
            field=models.ManyToManyField(through='sitelogic.PublicationCategory', to='sitelogic.category'),
        ),
    ]
